GreenNote.Web/Controllers/AuthController.cs
using GreenNote.Web.Models;
using GreenNote.Web.Services.IServices;
using GreenNote.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace GreenNote.Web.Controllers
{
	public class AuthController : Controller
	{
		private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;

		public AuthController(IAuthService authService,ITokenProvider tokenProvider)
		{
			_authService = authService;
            _tokenProvider= tokenProvider;

        }

        [HttpGet]
		public async Task<IActionResult> Login()
		{
            LoginRequestDto loginRequestDto = new();
			return View(loginRequestDto);
		}

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto obj)
        {
            ResponseDto responseDto = await _authService.LoginAsync(obj);

            if (responseDto != null && responseDto.IsSuccess)
            {
                LoginResponseDto loginResponseDto =
                    JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result));

                await SignInUser(loginResponseDto);
                _tokenProvider.SetToken(loginResponseDto.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = responseDto.Message;
                return View(obj);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer}
            };

            ViewBag.RoleList = roleList;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationRequestDto registrationRequestDto)
        {
            ResponseDto result = await _authService.RegisterAsync(registrationRequestDto);
            ResponseDto assingRole;

            if (result != null && result.IsSuccess)
            {
                if (string.IsNullOrEmpty(registrationRequestDto.Role))
                {
                    registrationRequestDto.Role = SD.RoleCustomer;
                }
                assingRole = await _authService.AssignRoleAsync(registrationRequestDto);

                if (assingRole != null && assingRole.IsSuccess)
                {
                    TempData["success"] = "Registration Successful";
                    return RedirectToAction(nameof(Login));
                }
            }
            else
            {
                TempData["error"] = result.Message;
            }


            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer}
            };

            ViewBag.RoleList = roleList;
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }

        private async Task SignInUser(LoginResponseDto model)
        {
            var handler = new JwtSecurityTokenHandler();

            var jwt = handler.ReadJwtToken(model.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name,
               jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role,
               jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));

            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }

    }
}

GreenNote.Web/Controllers/ClassInfoController.cs
using GreenNote.Web.Models;
using GreenNote.Web.Models.StudentNameList;
using GreenNote.Web.Services.IServices;
using GreenNote.Web.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace GreenNote.Web.Controllers
{
    public class ClassInfoController : Controller
    {
        private readonly IClassInfoService _classInfoService;
        private readonly StudentNamelist _studentNameList;

        public ClassInfoController(IClassInfoService classInfoService)
        {
            _classInfoService = classInfoService;
            _studentNameList = new StudentNamelist();
            
        }

        public async Task<IActionResult> ClassInfoAllView()
        {
            List<ClassInfoDto> list = new();
            ResponseDto response = await _classInfoService.GetAllAsync();

            if (response != null && response.IsSuccess == true)
            {
                list = JsonConvert.DeserializeObject<List<ClassInfoDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response.Message;
            }

            var studentNameList = _studentNameList.NameList;



            ViewBag.StudentNameList = studentNameList;

            return View(list);
        }

        public async Task<IActionResult> ClassInfoDetail(int classInfoId)
        {
            ResponseDto response = await _classInfoService.GetOneDataAsync(classInfoId);
            ClassInfoDto classInfoDto = new();
            classInfoDto = JsonConvert.DeserializeObject<ClassInfoDto>(Convert.ToString(response.Result));
            return View(classInfoDto);
        }



        public async Task<IActionResult> ClassInfoIndex(string studentName)
        {
            if (studentName == null)
            {
                List<ClassInfoDto> list = new();
                ResponseDto response = await _classInfoService.GetAllAsync();

                if (response != null && response.IsSuccess == true)
                {
                    list = JsonConvert.DeserializeObject<List<ClassInfoDto>>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["error"] = response.Message;
                }

                //비효율적
                var studentNameList = _studentNameList.NameList;
                ViewBag.StudentNameList = studentNameList;

                return View(list);
            }
            else
            {
                List<ClassInfoDto> list = new();
                ResponseDto response = await _classInfoService.GetStudentAsync(studentName);

                if (response != null && response.IsSuccess == true)
                {
                    list = JsonConvert.DeserializeObject<List<ClassInfoDto>>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["error"] = response.Message;
                }

                var studentNameList = _studentNameList.NameList;


                ViewBag.StudentNameList = studentNameList;

                return View(list);
            }
        }


        public async Task<IActionResult> ClassInfoCreate()
        {
            //비효율적
            var studentNameList = _studentNameList.NameList;
            ViewBag.StudentNameList = studentNameList;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ClassInfoCreate(ClassInfoDto classInfoDto)
        {
            

            if (ModelState.IsValid)
            {
                ResponseDto? response = await _classInfoService.CreateAsync(classInfoDto);

                if (response != null && response.IsSuccess == true)
                {
                    TempData["Success"] = "ClassInfo Created Successfully";
                    return RedirectToAction(nameof(ClassInfoIndex));
                }
                else
                {
                    TempData["Error"] = response?.Message;
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ClassInfoDelete(int id)
        {
            ResponseDto? response = await _classInfoService.DeleteAsync(id);
            TempData["Success"] = "Delete a ClassInfo";
            return RedirectToAction(nameof(ClassInfoIndex));
        }

        [HttpPost]
        public async Task<IActionResult> ClassInfoUpdate(ClassInfoDto classInfoDto)
        {
            if (ModelState.IsValid)
            {
            ResponseDto? response = await _classInfoService.UpdateAsync(classInfoDto);
                if (response != null && response.IsSuccess == true)
                {
                TempData["Success"] = "Update is Success";
                return RedirectToAction(nameof(ClassInfoIndex));

                }
                else
                {
                TempData["Error"] = response.Message;
                    return View();
                }
            }
            else
            {
            return View();
            }
        }
    }
}

GreenNote.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GreenNote.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="~/GreenNote.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GreenNote.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="ClassInfo" asp-action="ClassInfoIndex"><i class="bi bi-journal-text">수업 관리</i></a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello, @User.Identity.Name</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications"/>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <i class="bi bi-person-arms-up"></i>2023 - GreenNote.Web by .Net8
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GreenNote.Web/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}